version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
      - alembic:/app/alembic
      - photo:/app/photo
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  alembic:
  photo:
  postgres_data: