"""f2024-05-21 20:51

Revision ID: 0900f22ed890
Revises: 3ec550b14a2c
Create Date: 2024-05-21 20:51:51.346839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0900f22ed890'
down_revision: Union[str, None] = '3ec550b14a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
