"""f2024-05-21 20:50

Revision ID: 3ec550b14a2c
Revises: 
Create Date: 2024-05-21 20:50:03.775040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec550b14a2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('user_age', sa.Integer(), nullable=True))
    op.drop_index('ix_user_profiles_ass_size', table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_user_age'), 'user_profiles', ['user_age'], unique=False)
    op.drop_constraint('user_profiles_user_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_profiles', 'ass_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('ass_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key('user_profiles_user_id_fkey', 'user_profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_profiles_user_age'), table_name='user_profiles')
    op.create_index('ix_user_profiles_ass_size', 'user_profiles', ['ass_size'], unique=False)
    op.drop_column('user_profiles', 'user_age')
    # ### end Alembic commands ###
