"""f2024-05-21 22:02

Revision ID: 7d8cc4a5c790
Revises: 0900f22ed890
Create Date: 2024-05-21 22:02:26.387734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8cc4a5c790'
down_revision: Union[str, None] = '0900f22ed890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('user_photo', sa.String(), nullable=True))
    op.drop_index('ix_user_profiles_photo', table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_user_photo'), 'user_profiles', ['user_photo'], unique=False)
    op.drop_column('user_profiles', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_profiles_user_photo'), table_name='user_profiles')
    op.create_index('ix_user_profiles_photo', 'user_profiles', ['photo'], unique=False)
    op.drop_column('user_profiles', 'user_photo')
    # ### end Alembic commands ###
